### ISSUE TITLE
Followup tracking after #158

### ISSUE THREAD

**Issue by eatonphil** [multiprocessio/datastation#159]
* [x] Test Snowflake
* [x] Test Prometheus
* [x] Fix macos http test

Tutorials:

* [x] Influx, Influx2 and FluxQL
* [x] Prometheus
* [ ] Cassandra
* [ ] Snowflake
* [ ] SQLite (not read-only copy when doing remote proxy)

**Comment by eatonphil** [comment]
This is now being tracked in https://github.com/multiprocessio/datastation-documentation
