### ISSUE TITLE
Release 0.3.0 checklist

### ISSUE THREAD

**Issue by eatonphil** [multiprocessio/datastation#81]
Definitely:
* [X] Systemd service for running the server and export crons
* [x] Server install instructions/documentation
* [x] TLS not required, migrations should be handled by the server
* [x] Builtin functions explainer is impossible to read
* [x] Copy datastation-documentation into site
* [x] Docs portion of site should have link back to repo and should have working header anchor/links

Maybe?
* [x] Fix up UI for scheduling and dashboards
* [ ] Invalid dependent results in filter aggregate panel are not formatted correctly, whole stacktrace is shown
* [ ] Changing tabs is slow
* [ ] Server reloads a few times when loading onto a project

Bugs
* [x] Editing input text hangs pretty frequently, maybe on save

## Draft of release notes

* Dashboard mode
* Scheduled email exports
* Faster panel runs
* Named DM_getPanel('my panel name') calls
* All panels details are collapseable
* Install scripts and built artifacts for server deploy
* Graphing panel updates (size, unique color, line charts)

**Comment by eatonphil** [comment]
Invalid dependent panel results are not correct after the panelSource uuid refactor

![image](https://user-images.githubusercontent.com/3925912/140403963-df474826-88ea-4481-9cc5-1612103d8c33.png)

**Comment by eatonphil** [comment]
Page crashes loading when creating a first page on a new project

![image](https://user-images.githubusercontent.com/3925912/141040062-b5080ced-649d-4408-8646-269d12452498.png)

**Comment by eatonphil** [comment]
Cannot run any panels on new page

![image](https://user-images.githubusercontent.com/3925912/141144611-86da94b6-0c08-448b-98ee-93e01265a990.png)

**Comment by eatonphil** [comment]
This release is long done!
